app/helpers/main_menu_helper.rb, db/seeds.rb, lib/cms/hippo_import.rb, lib/tasks/b2b.rake
Three things:
* Refactor one method of Hippo Importer (is not related to the feature development, but was related to investigate the actual structure of Hippo articles)
* Remove layouts from menu like the P.O requested.
* Adding a rake task to create the corporate article type.
=> B2b creating corporate page

app/assets/stylesheets/comfortable_mexican_sofa/admin/helpers/_fixedsticky.scss
Makes it easier to see the toolbar when it is fixed.
=> Adds drop shadow underneath fixed toolbar

app/assets/stylesheets/comfortable_mexican_sofa/admin/base/_forms.scss, app/assets/stylesheets/comfortable_mexican_sofa/admin/lib/_variables.scss
=> Fix white text on select boxes when zooming on CMS HP

app/assets/stylesheets/comfortable_mexican_sofa/admin/base/_forms.scss, app/assets/stylesheets/comfortable_mexican_sofa/admin/lib/_variables.scss, app/views/pages/_form.html.haml
Exceeded characters and icon now highlighted in red
=> Adds text formatting to character count.

app/assets/javascripts/comfortable_mexican_sofa/admin/modules/MASEditor.js, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/mastalk/snippets-model.js, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/mastalk/snippets/video-brightcove.md, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/mastalk/snippets/video-youtube.md, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/mastalk/snippets/video.md, app/assets/javascripts/require_config.js.erb, app/views/comfy/admin/cms/pages/_toolbar.haml, spec/javascripts/test-main.js
- Adds button for Brightcove video snippets
- Use RequireJS path alias instead of explicit declaration for each snippet
=> Add Brightcove snippet button

app/models/comfy/cms/page.rb, config/initializers/comfortable_mexican_sofa.rb, lib/cms/category_import.rb, lib/comfortable_mexican_sofa/extensions/is_taggable.rb, spec/factories/categories.rb
Silenced if they're understandable, fixed if they're not.
Since I noticed @tomas-stefano's gist moving us towards pre-commit code style checking hooks, figured an all-green rubocop round would be a good thing.
Feel free to push straight to this branch if you think it should be done a different way.
=> Code style fixes.

app/assets/javascripts/comfortable_mexican_sofa/admin/modules/WordCount.js, app/assets/javascripts/require_config.js.erb, app/assets/stylesheets/comfortable_mexican_sofa/admin/state/_editor.scss, app/views/comfy/admin/cms/pages/_editor.html.haml, app/views/pages/_form.html.haml, spec/javascripts/fixtures/WordCount.html, spec/javascripts/test-main.js, spec/javascripts/tests/WordCount_spec.js
Adds (approximate) word count functionality to the Layout view on the Article page.
=> Add WordCount component

app/controllers/api/content_controller.rb, app/presenters/page_presenter.rb, spec/controllers/api/content_controller_spec.rb, spec/presenters/page_presenter_spec.rb
*[DO NOT MERGE]* - Need some work on frontend repository.
=> Preview by page type (action plans, news, videos, articles and corporate)

app/models/comfy/cms/page.rb, app/presenters/page_presenter.rb, app/serializers/page_serializer.rb, app/serializers/page_translation_serializer.rb, spec/controllers/api/content_controller_spec.rb
[DO NOT MERGE] - Need some work on frontend repository.
=> Page translation api

app/assets/javascripts/comfortable_mexican_sofa/admin/modules/ListSorter.js, app/assets/stylesheets/comfortable_mexican_sofa/admin/components/_sortable-list.scss, app/assets/stylesheets/comfortable_mexican_sofa/admin/components/common/_panel.scss, app/assets/stylesheets/comfortable_mexican_sofa/admin/lib/_variables.scss, app/helpers/main_menu_helper.rb, app/views/categories/_form.html.haml, app/views/categories/index.html.haml, app/views/categories/show.html.haml, config/locales/categories.yml, config/locales/menu.yml
Some minor formatting tweaks to improve the formatting of the Category manager.
=> Category manager frontend updates

app/assets/stylesheets/comfortable_mexican_sofa/admin/components/_dialog.scss
Strangely, my previous fix worked locally, but not on QA. This one *should* do it :four_leaf_clover: 
Previous [PR](https://github.com/moneyadviceservice/cms/pull/164) with issue explained.
@moneyadviceservice/frontend
=> Further fix for Dialog rendering on InsertManager

app/helpers/pages_helper.rb, app/views/pages/_form.html.haml, spec/helpers/pages_helper_spec.rb
Fixed by @tomas-stefano and @ourmaninamsterdam
TP#5890
=> Fix for Meta title input not being populated

app/views/hippos/new.html.haml, lib/cms/hippo_importer/corporate_articles_guide.rb
The last articles to migration to B2b are Guide type on Hippo. Need to create a class to map that
=> Add corporate articles guide

app/views/categories/_form.html.haml, app/views/categories/show.html.haml, config/locales/categories.yml
=> Update Category Manager checkbox label

app/assets/stylesheets/comfortable_mexican_sofa/admin/components/common/_tables.scss, app/views/pages/_index_branch.html.haml
Also stops all columns from narrowing too much.
=> Increase width of Page title column

app/assets/javascripts/comfortable_mexican_sofa/admin/modules/scribe/scribe-plugin-image-inserter.js
This ensures the selection is made available to Scribe when the Dialog has opened. TP#5999
=> Fix image insertion

app/assets/stylesheets/comfortable_mexican_sofa/admin/components/_content_grid.scss, app/assets/stylesheets/comfortable_mexican_sofa/admin/components/_page.scss, app/assets/stylesheets/comfortable_mexican_sofa/admin/components/_pagination.scss, app/assets/stylesheets/comfortable_mexican_sofa/admin/components/common/_panel.scss, app/assets/stylesheets/comfortable_mexican_sofa/admin/components/common/_tables.scss, app/assets/stylesheets/comfortable_mexican_sofa/admin/layout/_panel_content.scss, app/assets/stylesheets/comfortable_mexican_sofa/admin/lib/_variables.scss, app/controllers/pages_controller.rb, app/views/categories/index.html.haml, app/views/categories/new.html.haml, app/views/categories/show.html.haml, app/views/comfy/admin/cms/pages/_draft_pages.html.haml, app/views/comfy/admin/cms/pages/_last_published_pages.html.haml, app/views/files/index.html.haml, app/views/pages/index.html.haml, app/views/users/_form.html.haml, app/views/users/edit.html.haml, app/views/users/index.html.haml, app/views/users/new.html.haml
Implements CMS dashboard design
=> Dashboard updates

app/assets/stylesheets/comfortable_mexican_sofa/admin/components/_nav_primary.scss, app/assets/stylesheets/comfortable_mexican_sofa/admin/components/common/_panel.scss, app/assets/stylesheets/comfortable_mexican_sofa/admin/layout/_panel_content.scss, app/assets/stylesheets/comfortable_mexican_sofa/admin/layout/components/_search_bar.scss, app/assets/stylesheets/comfortable_mexican_sofa/admin/lib/_variables.scss, app/views/layouts/comfy/admin/cms/_nav_main.html.haml, app/views/pages/index.html.haml
This is the same as https://github.com/moneyadviceservice/cms/pull/186 but this one includes a fix for the failing Cucumber test.
=> Add search bar to header

app/views/pages/_form.html.haml
=> Omit the Activity Log from new article page

app/assets/stylesheets/comfortable_mexican_sofa/admin/base/_forms.scss, app/assets/stylesheets/comfortable_mexican_sofa/admin/lib/_variables.scss, app/models/comfy/cms/page.rb, app/views/pages/_form.html.haml, spec/models/comfy/cms/page_spec.rb
@tomas-stefano and I will pair on some acceptance tests in the near future when availability allows...
TP#4964
=> Disable URL editing after article is published.

app/assets/javascripts/comfortable_mexican_sofa/admin/modules/FieldDisabledStateToggler.js, app/assets/javascripts/require_config.js.erb, app/assets/stylesheets/comfortable_mexican_sofa/admin/base/_forms.scss, app/helpers/pages_helper.rb, app/views/pages/_form.html.haml, spec/helpers/pages_helper_spec.rb, spec/javascripts/fixtures/FieldDisabledStateToggler.html, spec/javascripts/test-main.js, spec/javascripts/tests/FieldDisabledStateToggler_spec.js
This enables a disabled/readonly input field on double click and disables it on blur.
=> Add FieldDisabledStateToggler component

README.md, bin/setup
The README for this repo needs a little TLC with some up to date instructions on how to set the CMS up. I decided to do a little clean up as well as set up a convenient script to help bootstrap the whole thing.
=> Improve setup

app/assets/javascripts/comfortable_mexican_sofa/admin/modules/mastalk/snippets-model.js
=> Swap promo block image and content ordering

bin/setup
The `seeds.rb` file doesn't create these.
=> Seed corporate and video layouts

app/controllers/api/content_controller.rb, app/models/comfy/cms/page.rb, spec/controllers/api/content_controller_spec.rb, spec/factories/layouts.rb
e.g. feeds for videos, news etc
=> add partner feeds for other page types

config/categories.yml, db/seeds.rb
Updates the seeds file to set up categories needed to run Contento locally correctly.
=> Seed categories correctly

app/models/comfy/cms/page.rb, app/serializers/page_serializer.rb, spec/models/comfy/cms/page_spec.rb
=> add published_at to serializer

app/models/comfy/cms/page.rb, app/serializers/page_link/base.rb, spec/serializers/page_links/next_link_spec.rb, spec/serializers/page_links/previous_link_spec.rb, spec/serializers/page_serializer_spec.rb
previously all pages were incorrectly considered articles only
=> page links now consider their layout

app/serializers/page_link/base.rb, spec/serializers/page_serializer_spec.rb
this uses the ordinal value on the categorization
=> next and previous links now correctly ordered

app/assets/javascripts/application.js, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/EmbeddedGoogleAnalytics.js, app/assets/javascripts/require_config.js.erb, app/assets/stylesheets/comfortable_mexican_sofa/admin/layout/common/_common.scss, app/views/pages/_form.html.haml, app/views/pages/edit.html.erb, app/views/pages/edit.html.haml, bower.json.erb, config/initializers/assets.rb, spec/javascripts/fixtures/EmbeddedGoogleAnalytics.html, spec/javascripts/test-main.js, spec/javascripts/tests/EmbeddedGoogleAnalytics_spec.js
This adds inline google analytics to the cms when editing a page
Unfortunately testing is limited due to how it interacts with the google api. Although if anyone has any thoughts on how to improve this please share.
=> Google analytics

app/controllers/categories_controller.rb, app/models/comfy/cms/category.rb, app/serializers/category_serializer.rb, app/views/categories/show.html.haml, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, db/migrate/20150605153628_add_file_to_category.rb, db/schema.rb, spec/models/comfy/cms/category_spec.rb, spec/serializers/category_serializer_spec.rb
users can associate a small and large image to a category
via the category page
=> Add category images

app/controllers/categories_controller.rb, app/models/category_promo.rb, app/models/comfy/cms/category.rb, app/serializers/category_promo_serializer.rb, app/serializers/category_serializer.rb, app/views/categories/show.html.haml, config/locales/category_promos.yml, db/migrate/20150612153536_create_category_promos.rb, db/schema.rb, spec/controllers/categories_controller_spec.rb, spec/models/category_promo_spec.rb, spec/models/comfy/cms/category_spec.rb, spec/serializers/category_promo_serializer_spec.rb, spec/serializers/category_serializer_spec.rb
- This allows the cms to add promoted items to a category
=> Category promo

app/models/block_composer.rb, app/models/table_wrapper.rb, spec/models/block_composer_spec.rb, spec/models/table_wrapper_spec.rb
- Kramdown library isn't very extensisble so not done at that level
- this is done to enable scrollable tables
=> post process html output to wrap table elements

app/assets/javascripts/comfortable_mexican_sofa/admin/modules/MASEditor.js, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/scribe/scribe-plugin-image-inserter.js, app/presenters/file_presenter.rb, app/views/links/images/_listing.html.haml, config/locales/files.yml, spec/presenters/file_presenter_spec.rb
- Also changed file description label to 'Alt text' so editors are aware of what the field will be used for
=> inserting an image adds description as alt text

app/assets/javascripts/comfortable_mexican_sofa/admin/modules/MASEditor.js
so editors hovering over links will have useful titles
=> whitelist tiles attribute on links

config/routes.rb, spec/requests/api_spec.rb
to prevent collision with the rest of the application
=> add additional namespaced api endpoint

Gemfile, Gemfile.lock
As this file is created by Puppet for each environment, we need to test
that it creates one for prod. Even though the cms is not deployed
through puppet, there could be some config in there which initially set
things up. If not then we’ll recommit this yaml file. (+1 squashed commit)
Squashed commits:
[1a0693b] Set up New Relic
=> Just bundle new relic gems not yaml.

Gemfile, Gemfile.lock, config/features/development.yml, config/features/production.yml, config/features/qa.yml, config/features/test.yml, config/initializers/features.rb
- Since our infrastructure isn't automated, I'm not able to inject things at environmental level. So I've done this at app level.
- Detect the current environment via various means
- Pull in the appropriate feature toggles
=> Feature toggling

app/assets/stylesheets/comfortable_mexican_sofa/admin/components/_nav_article.scss, app/controllers/redirects_controller.rb, app/views/redirects/index.html.erb, app/views/redirects/show.html.erb, spec/controllers/redirects_controller_spec.rb
Redirects index
Changing a redirect
=> able to edit redirects

db/migrate/20150903104729_index_redirect_source.rb, db/schema.rb
as we will be doing lookups via the source we want to index this
=> add index on redirects source

app/models/redirect.rb, spec/models/redirect_spec.rb
=> Redirect fixes

app/controllers/redirects_controller.rb, app/helpers/main_menu_helper.rb, config/locales/menu.yml, spec/controllers/redirects_controller_spec.rb
- only admins can see this in their nav
- only admins will be able to access the redirects functionality
=> Add redirects to nav menu

app/serializers/page_link/latest_links.rb, config/environments/production.rb, config/environments/test.rb
this should reduce frontend load times on certain pages by 75%
=> cache blog links for a minute

Gemfile, Gemfile.lock
Bumping mastalk version to include ?rel=0 on youtube videos
=> Updating mastalk version

app/assets/javascripts/comfortable_mexican_sofa/admin/modules/CategoryExpand.js, app/assets/javascripts/require_config.js.erb, app/presenters/page_presenter.rb, app/views/comfy/cms/pages/_page.html.haml, app/views/pages/_index_branch.html.haml, spec/presenters/page_presenter_spec.rb
Allows a user to expand the list of categories on the CMS homepage
=> [DEV APPROVED] Category expand

Gemfile, Gemfile.lock, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/MASEditor.js, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/mastalk/snippets-model.js, app/views/comfy/admin/cms/pages/_toolbar.haml
Enabling an editor to embed Vimeo videos, Relates to https://github.com/moneyadviceservice/mastalk/pull/12
=> [DEV APPROVED] Adding Vimeo embed snippet

app/helpers/pages_helper.rb, app/views/pages/_footer_bar.html.haml, app/views/pages/_form.html.haml, app/views/pages/_form_additional_options.html.haml, app/views/pages/_form_for_home_page.html.haml, app/views/pages/_form_layout.html.haml, app/views/pages/_form_meta_description.html.haml, app/views/pages/_form_meta_title.html.haml, app/views/pages/_form_save.html.haml, app/views/pages/_form_slug.html.haml, app/views/pages/_form_title.html.haml, app/views/pages/edit.html.erb, config/locales/pages.yml
- remove unused fields
- improve field labels
- added capability to render different forms based on the page layout
=> Tidy home page editing form

spec/javascripts/tests/EmbeddedGoogleAnalytics_spec.js
fixes phamtomjs test for googleAnalytics
=> update EmbeddedGoogleAnalytics karma test

.env.dev, .gitignore, Gemfile, Gemfile.lock, config/initializers/comfortable_mexican_sofa.rb
https://github.com/moneyadviceservice/cms/pull/307
=> 6981 cms upload through azure

app/models/redirect_version.rb, app/presenters/redirect_versions_presenter.rb, app/views/redirects/index.html.erb, spec/presenters/redirect_versions_presenter_spec.rb
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/cms/316)
=> [DEV APPROVED] 6959 fix redirects on admin dashboard

Gemfile, Gemfile.lock
Our gems source is now in Azure.
=> Change MAS gem source to gems.dev.mas.local

Gemfile, Gemfile.lock, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/mastalk/snippets-model.js
The bulk of this change comes in a [PR on the mastalk gem](https://github.com/moneyadviceservice/mastalk/pull/19) which introduces new snippet formats for accessible video embeds.
This PR simply pulls in the new gem and updates the javascript that inserts placeholder/template copy appropriately.
=> 7482 - a way to add a title to embedded videos

Gemfile, Gemfile.lock, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/mastalk/snippets-model.js
I screwed up and forgot to push up some rebasing and squashing before I merged [the original PR](https://github.com/moneyadviceservice/cms/pull/332) for this branch, so I've force pushed master back to how it was, and I'm opening this new PR for the correctly rewritten branch.
=> 7482 accessible video iframes (pull re-request)

app/models/page_feedback.rb, app/serializers/page_feedback_serializer.rb, spec/models/page_feedback_spec.rb
**Feature**
Returns page feedback counts for like and dislike after creating feedback.
[7663](https://moneyadviceservice.tpondemand.com/entity/7663)
closes #345
=> #7663 Return page feedback like/dislike count

Gemfile.lock, app/models/content_composer.rb, app/models/external_link.rb, app/models/table_wrapper.rb, app/serializers/block_serializer.rb, spec/models/content_composer_spec.rb, spec/models/external_link_spec.rb, spec/models/table_wrapper_spec.rb
**Feature**
Append visually hidden tag to improve accessibility for screen readers.
[Card 7669](https://moneyadviceservice.tpondemand.com/entity/7669)
Dev: @tomas-stefano @jriga
=> [DEV APPROVED] Added `ExternalLink` post processor for screen readers 

app/models/page_feedback.rb, app/serializers/page_feedback_serializer.rb, spec/models/page_feedback_spec.rb
* Add a validation on "shared_on" attribute;
* Rename count nodes to likes_count and dislikes_count for easier to parse on the client (it is not difficult the old one but this one will be easier).
=> [DEV APPROVED] Page feedback API improvements

Gemfile.lock, app/models/content_composer.rb, app/models/internal_link.rb, bin/rspec, bin/spring, spec/models/content_composer_spec.rb, spec/models/internal_link_spec.rb
**Feature**
[Card 7709](https://moneyadviceservice.tpondemand.com/entity/7709)
**Solution**
Added a internal link post processor to generate the menu after the `h1 + p` tags
=> [DEV APPROVED] 7709 internal links snippet

app/models/internal_link.rb, spec/models/internal_link_spec.rb
**Bug**
Some of the internal links menu were not properly detected and the menu was rendered a second time.
**Fix**
Improved the detection of existing internal links menu
=> [DEV APPROVED]Changed the way menu is detected to prevent double menu rendering

config/feature_toggles/production.yml
=> Enable page feedback feature on production! Yay

app/controllers/api/clumps_controller.rb, app/controllers/clumps_controller.rb, app/helpers/main_menu_helper.rb, app/models/clump.rb, app/models/clumping.rb, app/models/comfy/cms/category.rb, app/serializers/clump_serializer.rb, app/views/clumps/index.html.haml, config/routes.rb, db/migrate/20161118113307_create_clumps.rb, db/migrate/20161118115306_create_clumpings.rb, db/migrate/20161118135342_create_initial_clumps.rb, db/schema.rb
Recreating [this original PR](https://github.com/moneyadviceservice/cms/pull/362) that was based on `master` to instead come off the global nav feature branch of `global-nav-master`.
=> 7805 navigation categories activerecord

app/models/comfy/cms/page.rb, config/feature_toggles/qa.yml, spec/models/comfy/cms/page_spec.rb
Otherwise they will leave orphan records.
=> [DEV APPROVED] - Delete all feedback when page is destroyed

app/models/comfy/cms/category.rb, app/serializers/category_serializer.rb, config/environments/development.rb, db/global_nav_category_setup.rb, db/migrate/20161121120920_add_legacy_parent_to_comfy_cms_category.rb, db/schema.rb, spec/serializers/category_serializer_spec.rb
**Context**
Global Nav works changes the current categories. This PR does:
=> [DEV APPROVED]7804 categories setup

app/views/pages/_index_branch.html.haml
* changed from URL to path
* the URL contains the full resource locator. This makes a request from an unsecured source for a secure resource.
=> [DEV APPROVED]change dynamically rendered route to path

app/serializers/clump_category_serializer.rb, app/serializers/clump_serializer.rb
=> [DEV APPROVED] - 7945 - Introduce a dedicated serializer for categories returned by clumps

spec/javascripts/tests/LinkManager_spec.js
change function from expect .size() to .length for compatibility with latest versions of JQuery
=> [DEV APPROVED]fix failing karma test in LinkManager_spec.js

app/assets/stylesheets/comfortable_mexican_sofa/admin/helpers/_fixedsticky.scss, config/initializers/assets.rb
There were a couple of missed references to the remove filament sticky javascript plugin, this PR removes these.
Original PR: https://github.com/moneyadviceservice/cms/pull/384
=> [DEV APPROVED]Filament sticky removal cleanup

app/helpers/files_helper.rb, app/views/files/_form.html.haml, features/resize_blog_thumbnail_images.feature, features/step_definitions/resize_blog_thumbnail_images_steps.rb
* The CMS team would like to retain the original url. Please do not remove
this without consulting them on how they use this feature.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/cms/387)
=> [DEV APPROVED] Removes links for alternative styles.

lib/tasks/uc.rake
Adds support for loading content from the CMS. 
See https://github.com/moneyadviceservice/cms/pull/388
=> changes page slug to uc content title

package.json
https://moneyadviceservice.tpondemand.com/entity/9098-cms-update-npm-packages
In the process of working on the CMS to support the site-search replacement many of the NPM (Node Package Manager) packages were upgraded.  We did not have sufficient time to double-check the upgrades for completion, compatibility, and outstanding issues (including security vulnerabilities).
Following a more in depth review I have further upgraded packages.
=> [DEV APPROVED] Update NPM packages

Gemfile, Gemfile.lock
=> Add whenever to Gemfile

db/seeds/fincap.seeds.rb, features/pages_form/fincap_insight_pages.feature, features/step_definitions/fincap_pages_steps.rb, lib/tasks/fincap.rake, spec/factories/blocks.rb, spec/filters/document_provider_spec.rb
Rename `country_of_delivery` to `countries_of_delivery` for consistency
=> [DEV APPROVED] Update countries_of_delivery

config/schedule.rb
Update cron schedule to run Algolia index rake task everyday at 5am.
=> [DEV APPROVED] Set search:index rake task to every day 5am

db/seeds/fincap.seeds.rb
This block is needed for testing the qualitative / quantitative indicator on the fincap site.
=> [DEV APPROVED] Add data_types block to fincap seed data

db/seeds/fincap.seeds.rb, features/pages_form/fincap_evaluation_pages.feature, features/step_definitions/fincap_pages_steps.rb, features/support/ui/pages/edit.rb, lib/tasks/fincap.rake
[TP card](https://moneyadviceservice.tpondemand.com/entity/9188-create-evaluation-summary-cms)
This PR adds the evaluation page type to CMS.
This are the fields add to CMS (CMS names on the second column).
```
+-----------------------------+------------------------+------------+--|
|            Evaluation CMS Field Structure                            |
+-----------------------------+------------------------+---------------|
+-----------------------------+------------------------+---------------|
| PRISMIC Field               | identifier             | CMS Format    |
+-----------------------------+------------------------+---------------|
| client_groups               | client_groups          |Multiple Blocks|
| topics                      | topics                 |Multiple Blocks|
| …
```
=> Add evaluation page type to CMS

db/seeds/fincap.seeds.rb, lib/tasks/fincap.rake
[TP link](https://moneyadviceservice.tpondemand.com/entity/8861-thematic-review-cms-template)
This PR addresses the thematic review which is exactly the same as an article page. 
This PR only adds data, only data so I think that should not be any test since we already have tests to guarantee that this data shows the right fields.
=> Add thematic review to fincap cms

db/seeds/fincap.seeds.rb, features/pages_form/fincap_thematic_reviews_landing_page.feature, features/step_definitions/fincap_pages_steps.rb, lib/tasks/fincap.rake
[TP 9202](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/4646449523824205368&appConfig=eyJhY2lkIjoiRTQ4MDEyNENDOUYxRDU4RDg0RTEyRjNCODBEN0VBMUYifQ==&searchPopup=userstory/9202)
This PR adds the Thematic Reviews Landing page type to CMS. There is only one editable rich text field for this page type.
=> Add thematic reviews landing page type

features/pages_form/mas_footer_pages.feature, features/pages_form/mas_homepage_pages.feature, features/step_definitions/mas_pages_steps.rb, features/support/ui/pages/edit.rb, lib/cms/form_builder.rb
[TP 9282](https://moneyadviceservice.tpondemand.com/entity/9282-bug-mas-cms-homepage-and-footer)
During the Fincap work we made the decision to move away from
ComfortableMexicanSofa's FormBuilder and to utilize ActionView
class Cms::FormBuilder < ActionView::Helpers::FormBuilder
With this change some of the methods used to build the MAS homepage and
footer were lost and needed to be moved into the FormBuilder here.
Feature tests to cover this have been added as well
=> [DEV APPROVED] 9282 - Fix MAS CMS for homepage and footer layouts

db/seeds/fincap.seeds.rb, features/pages_form/fincap_lifestage_page.feature, features/step_definitions/fincap_pages_steps.rb, features/support/ui/pages/edit.rb, lib/tasks/fincap.rake
[TP 9240](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5580782241563718174&appConfig=eyJhY2lkIjoiRTQ4MDEyNENDOUYxRDU4RDg0RTEyRjNCODBEN0VBMUYifQ==&searchPopup=userstory/9240)
Facility for editors to create lifestage pages for displaying on the Fincap website. 
Create a lifestage page layout in CMS to include a number of editable fields as specified in the TP card.
=> 9240 Create a Lifestage layout

db/seeds/fincap_data/homepage_seeds.rb, features/pages_form/fincap_homepage_page.feature, features/step_definitions/fincap_background_steps.rb, features/support/ui/pages/edit.rb, lib/tasks/fincap.rake
[TP 9262](https://moneyadviceservice.tpondemand.com/restui/board.aspx#page=board/5481321774608038243&appConfig=eyJhY2lkIjoiNjRGM0FCMDY3RUQ5MDREM0RGNDZGOUM0REZENUZBMzIifQ==&searchPopup=userstory/9262)
Content editors need to create the content for the Fincap website homepage.
=> Create layout for the homepage

lib/prismic/cms_converter.rb, lib/prismic/converted_document.rb, lib/prismic/html_converter.rb, lib/prismic/migrator/article.rb, lib/prismic/migrator/base.rb, lib/prismic/migrator/evaluation.rb, lib/prismic/migrator/evidence_hub.rb, lib/prismic/migrator/insight.rb, lib/prismic/migrator/review.rb, lib/prismic/tag_converter.rb, lib/tasks/prismic.rake, spec/lib/prismic/cms_converter_spec.rb, spec/lib/prismic/migrator/article_spec.rb, spec/lib/prismic/migrator/evaluation_spec.rb, spec/lib/prismic/migrator/insight_spec.rb, spec/lib/prismic/migrator/review_spec.rb
This code will be run only once so I don't think there should be a review. But opened the PR for documenting the change.
So this PR addresses the following migration from prismic:
On my local machine that's the feedback that I received:
```
...S.............F.................SS.SS.SS.......S........S.....S.........
..S...FS..F..........F...FS....S...........S......................SS....S.SSS.
..............S................................S....................................S...S..
.....S.SS....................................................................................
................................................................................................
..S................................S......
477 documents. 442 migrated, 30 skipped, 5 errors
Failed migration from …
```
=> Fincap evidence hub migration

db/seeds/fincap_data/homepage_seeds.rb, features/pages_form/fincap_homepage_page.feature, features/step_definitions/fincap_background_steps.rb, lib/tasks/fincap.rake
The fincap homepage does not display any links to files for downloading.
- remove downloads component
- in the seeds, change homepage slug to be 'root'
=> [DEV APPROVED] Changes for homepage layout

Gemfile, README.md
- Remove warning by placing `unicorn-rails` into a shared group
- Amend README adding mysql config to avoid compiling extensions issues
=> [DEV APPROVED] Remove setup warning and amend README

db/seeds/fincap_data/redirects.rb
[TP card](https://moneyadviceservice.tpondemand.com/entity/9225-implement-internal-redirect-feature-on-fincap)
This PR adds seeds for the PR https://github.com/moneyadviceservice/fin_cap/pull/184
=> [DEV APPROVED] Add seeds for redirects on fincap app

config/schedule.rb
Add schedule config for fincap-cms algolia to create crontab
=> [DEV APPROVED] 9512 Add schedule for fincap-cms algolia indexing whenever gem

db/seeds/fincap_data/news_seeds.rb
[TP card](https://moneyadviceservice.tpondemand.com/entity/9500-latest-news-component-doesnt-show-most)
I created this data on the seeds to help me reproduce the bug (more details about the bug on tp link above).
I thought this seed would be useful on reproducing the bug and **also to help write the feature tests on fincap repo**.
=> [DEV APPROVED] Add more news to fincap seeds

db/seeds/fincap_data/evidence_summary_seeds.rb, db/seeds/fincap_data/lifestage.seeds.rb
[TP Card](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=userstory/9508)
Completes #483
In order to have a complete feature test for the Search feature (FINCAP) description needs to be added to the Seeds.
=> [DEV APPROVED] - [9508] Add dummy meta_description to seeds

lib/tasks/fincap.rake
Was added as part of https://github.com/moneyadviceservice/cms/pull/494, which required a one time run to fix the issue.
=> [DEV APPROVED] Remove rake task not needed anymore

Gemfile, Gemfile.lock
Reverts moneyadviceservice/cms#510
=> Revert "Lock Ruby Parser to v3.11"
