.env.dev, app/serializers/page_serializer.rb, lib/publify/api.rb, spec/lib/publify/api_spec.rb, spec/serializers/page_serializer_spec.rb
Note: 
'PUBLIFY_HOSTNAME' is set in .env for development.
For QA & production we set this up in the Scripts repo.
=> adding latest blog post links (form Publify) to page_serializer for frontend

app/assets/javascripts/comfortable_mexican_sofa/admin/modules/scribe/scribe-plugin-image-inserter.js, app/views/links/images/_listing.html.haml
Previously the images were being stretched to fit a 1:1 aspect ratio. This fix makes them fit to their native aspect ratios within the content grid.
=> Fix image aspect ratios on content grid

app/assets/stylesheets/comfortable_mexican_sofa/admin/components/_images.scss
The country toggle was wrapping beneath the country flag image. This floats it to the right of the toggle.
=> Fix country flag image layout

app/assets/stylesheets/comfortable_mexican_sofa/admin/layout/_editor.scss, app/controllers/pages_controller.rb, app/models/comfy/cms/page.rb, app/serializers/page_link/base.rb, app/views/pages/_form.html.haml, db/migrate/20150121145709_add_suppress_from_links_recirculation.rb, db/schema.rb, spec/controllers/pages_controller_spec.rb, spec/models/comfy/cms/page_spec.rb
This PR involves providing a checkbox in the Contento UI to suppress and article from being returned in the Related and Popular Links json.
When marking an article as suppressed, it's mirror in other languages should also be suppressed.
=> Suppress related and popular links

Gemfile, Gemfile.lock, README.md, config/schedule.rb
There was a decision to not use whenever for managing the cron. This is cleanup of the whenever gem and associated configuration
=> Remove whenever gem and config. Cron is managed by puppet scripts

Gemfile, Gemfile.lock, lib/clock.rb
We've decided to use Clockwork instead of using cron to rake task — setting up the environment from a cron task was proving troublesome and troublesome to test locally.
There's a corresponding PR for scripts to use this: https://github.com/moneyadviceservice/scripts/pull/155
=> Add Clockwork & task to make it UpdatePageViews.

lib/clock.rb, lib/cms/update_page_views_task.rb
I decided this wasn't getting logged anywhere because:
* Clockwork outputs to `STDOUT` by default.
* :sparkles:For some reason:sparkles: Rails.logger was doing the same.
* The init.d script in `scripts` pipes `STDOUT` to `/dev/null` by default.
I've reconfigured Clockwork to output to a logfile provided in a env variable, or STDOUT otherwise.
I've also added some more logging, and made the existing logging use the right logging levels.
Scripts PR here: https://github.com/moneyadviceservice/scripts/pull/160
=> Make UpdatePageViews take a passed-in logfile, log to right levels.

app/models/comfy/cms/page.rb, spec/models/comfy/cms/page_spec.rb
To guard against situations where the GA fetch task hasn't been run yet. 
(e.g. when we first deploy to production)
=> Prevents Page.most_popular returning pages with zero views.

app/controllers/api/content_controller.rb, app/controllers/api_controller.rb, app/controllers/category_contents_controller.rb, config/routes.rb, features/step_definitions/edit_page_steps.rb, features/support/ui/pages/live.rb, spec/controllers/api/content_controller_spec.rb, spec/factories/layouts.rb
With this PR is possible make GET requests to:
* /en/slug.json # Will see all pages
* /en/articles/slug.json # Only article page type
* /en/corporate/slug.json # Only corporate page type
* /en/action_plans/slug.json # Only action plan page type
* /en/videos/slug.json # Only videos page type
etc for all page types.
**Do not merge because it needs implement the client code on the frontend repository to requests for this resources.**
=> Content API separated by page type

app/assets/stylesheets/comfortable_mexican_sofa/admin/components/_dialog.scss
A prospective fix for the issue where the height of the Dialog is rendered shorter depending on how far you've scrolled down the page.
=> Fix for rendering issues on InsertManager Dialog

app/assets/stylesheets/comfortable_mexican_sofa/admin/base/_forms.scss, app/views/links/documents/_form.html.haml, app/views/links/pages/_form.html.haml
@moneyadviceservice/frontend
TP#5869
When we have an `<option>` with a long text label it is causing it to interfere with the layout ...
=> Add a fix to avoid select boxes affecting the layout

build.sh
* We try configure to the asset pipeline in order to see woff and ttf files without any success.
* Force in the build that make sure the fonts are in the public assets folder.
Another solution is appreciated.
=> Add missing fonts to the build.

app/controllers/hippo/diffs_controller.rb, app/views/hippo/diffs/show.html.haml, config/routes.rb, lib/cms/hippo_diff.rb, spec/controllers/hippo/diffs_controller_spec.rb, spec/lib/cms/hippo_diff_spec.rb
This is the simple version of the hippo diff page between hippo and Contento :tm: 
The perfect solution will be scraping the content xml file from Hippo instead expecting on the  tmp dir. Will do this in a separate PR.
=> Simple version - Hippo report tool

app/assets/javascripts/comfortable_mexican_sofa/admin/modules/scribe/scribe-plugin-linkeditor.js
It wasn't inserting the external link suffix when the last piece of text in a sentence was selected.
=> Fix external link suffix issue

app/models/comfy/cms/category.rb
Use require_dependency in order to stop errors in development mode, when rails reload the code.
=> Use require_dependency for comfy

app/assets/stylesheets/comfortable_mexican_sofa/admin/components/_nav_primary.scss, app/assets/stylesheets/comfortable_mexican_sofa/admin/components/common/_panel.scss, app/assets/stylesheets/comfortable_mexican_sofa/admin/layout/_panel_content.scss, app/assets/stylesheets/comfortable_mexican_sofa/admin/layout/components/_search_bar.scss, app/assets/stylesheets/comfortable_mexican_sofa/admin/lib/_variables.scss, app/views/layouts/comfy/admin/cms/_nav_main.html.haml, app/views/pages/index.html.haml
This will allow users to search from any page. Search results will appear on the homepage, as before.
Search functionality has been removed from the dashboard template.
=> Add search bar to header

app/assets/javascripts/comfortable_mexican_sofa/admin/modules/MASEditor.js, app/assets/javascripts/require_config.js.erb, app/assets/stylesheets/comfortable_mexican_sofa/admin/components/_editor.scss, bower.json.erb, config/initializers/assets.rb, spec/javascripts/test-main.js
This implements [Autogrow](https://github.com/ultimatedelman/autogrow) to automatically resize the Advanced mode textarea. This fixes the scrolling issues caused by editor-plugin-auto-resize-textarea when the box resized.
There are still some issues regarding the overlapping of the top and bottom fixed navigations, which I'll try to address on a future PR.
TP#6089
=> Fix Advanced mode textarea resize issues

app/assets/javascripts/comfortable_mexican_sofa/admin/modules/MASEditor.js, app/assets/javascripts/require_config.js.erb, app/assets/stylesheets/comfortable_mexican_sofa/admin/components/_editor.scss, bower.json.erb, config/initializers/assets.rb, spec/javascripts/helpers/shims/event.js, spec/javascripts/helpers/shims/phantom-shims.js, spec/javascripts/test-main.js
This replaces https://github.com/ultimatedelman/autogrow which proved to be buggy when resizing.
An `Event()` shim has been added to allow tests to run in PhantomJS until it arrives in v2.1.
=> Fix textarea autoresize in Advanced mode

Gemfile.lock, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/SearchBar.js, app/assets/javascripts/require_config.js.erb, app/views/layouts/comfy/admin/cms/_nav_main.html.haml, spec/javascripts/fixtures/SearchBar.html, spec/javascripts/test-main.js, spec/javascripts/tests/SearchBar_spec.js
The search input is now focussed when the Search icon is clicked. 
`Collapsable` emits a `toggler:toggled` event when it is triggerd. This component listens for said event and focusses the input.
Also bumps dough-ruby.
=> Search bar improvements

app/assets/javascripts/comfortable_mexican_sofa/admin/modules/AutoComplete.js, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/UnsavedChangesPrompt.js, app/assets/javascripts/require_config.js.erb, app/views/pages/_form.html.haml
Adds a component which watches elements within a container for any user input on form fields and `contentEditable` elements within. If the user makes a change and tries to navigate away or reload the page, a confirmation prompt is shown:
=> Add unsaved changes prompt

app/assets/javascripts/comfortable_mexican_sofa/admin/modules/FieldDisabledStateToggler.js, spec/javascripts/fixtures/FieldDisabledStateToggler.html, spec/javascripts/tests/FieldDisabledStateToggler_spec.js
Fixes a bug where users were unable to set the cursor position within the URL field.
@moneyadviceservice/team-bee 
id:6214
=> Allow placing of cursor in URL field

app/models/comfy/cms/page.rb, app/models/tag.rb, app/views/pages/_form.html.haml, spec/models/comfy/cms/page_spec.rb
by default a page is publishable unless tagged with do-not-publish
when not publishable admin UI to publish a page is removed
this feature will be used to provide content to engines
where we do not want articles to be published but still available
this is done by using the preview functionality as a back door
=> add Page#publishable?

app/controllers/categories_controller.rb, app/serializers/category_serializer.rb, app/views/categories/_form.html.haml, app/views/categories/show.html.haml, config/locales/categories.yml, db/migrate/20150428091610_add_third_level_nav_to_categories.rb, db/schema.rb, spec/controllers/categories_controller_spec.rb, spec/serializers/category_serializer_spec.rb
- add migration for third_level_navigation boolean to categories table
- this adds a tick box for third_level_navigation on category create and
edit page.
- expose third_level_navigation as part of the category show json
cc @darokel @tomas-stefano
=> add third_level_navigation to categories

app/assets/javascripts/comfortable_mexican_sofa/admin/modules/AutoComplete.js, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/CharacterCounter.js, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/Dialog.js, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/ElementFilter.js, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/ElementHider.js, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/FieldDisabledStateToggler.js, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/FileInputSubmit.js, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/ImageManager.js, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/InsertManager.js, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/LinkManager.js, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/ListSorter.js, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/MASEditor.js, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/MirrorInputValue.js, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/Popover.js, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/Scheduler.js, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/SearchBar.js, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/SelectSubmitter.js, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/SnippetInserter.js, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/StickyElements.js, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/TagManager.js, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/Tags.js, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/URLFormatter.js, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/URLToggler.js, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/UnsavedChangesPrompt.js, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/WordCount.js
Pending changes in Dough use `componentName` to stamp the attribute on the component element when it is initialised https://github.com/moneyadviceservice/dough/pull/219
=> Add componentNames to JS modules

Gemfile, Gemfile.lock, app/models/block_composer.rb, app/serializers/block_serializer.rb, features/step_definitions/edit_page_steps.rb, spec/models/block_composer_spec.rb, spec/serializers/block_serializer_spec.rb
- At the moment the CMS generates markdown content which is then processed by the client.
- This changes the API so it is now the job of the CMS to generate HTML.
- I think this is the job of the CMS and not the client hence the move
- This will save every client from having implement something to process the markdown (with custom snippets) to HTML
=> CMS api now serves HTML

app/controllers/api/content_controller.rb, app/models/comfy/cms/page.rb, config/routes.rb, spec/controllers/api/content_controller_spec.rb
This add partner feeds for published and unpublished articles.
- I'm pretty sure these feeds will be slow and we may need to consider some sort of caching mechanism.
=> Partner feeds for articles

app/serializers/page_serializer.rb, spec/serializers/page_serializer_spec.rb
this use to return the slug we now return /locale/page_type/slug
although this is a breaking change to the API I am not aware of any external
apps using they full_path at the moment
cc @tomas-stefano
=> make full_path in serializer useful

app/models/comfy/cms/page.rb, spec/models/comfy/cms/page_spec.rb
this may by due to off data in production
this bug manifests when the first revision event is nil
=> fix page#published_at when event is nil

app/models/comfy/cms/page.rb, db/migrate/20150608142817_add_published_at_to_page.rb, db/schema.rb, spec/models/comfy/cms/page_spec.rb
- Persist `published_at` when a page is published
- We will need to retrofit the `published_at` field for pages that are already published or have been published at some point
=> Persist published at

app/controllers/pages_controller.rb, app/views/pages/new.html.haml, spec/controllers/pages_controller_spec.rb
- On failed page creation this no longer raises an unexpected exception due to missing variables
- Slight hack to populate flash has with something meaningful. Comfy doesn't provide any hooks to make this possible.
=> Fix create page errors

app/assets/javascripts/comfortable_mexican_sofa/admin/modules/InsertManager.js, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/LinkManager.js, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/MASEditor.js, app/views/links/anchors/_form.html.haml, app/views/pages/_insert_link_dialog.html.haml, config/locales/links.yml, package.json, spec/javascripts/fixtures/LinkManager.html, spec/javascripts/karma.conf.js, spec/javascripts/tests/LinkManager_spec.js
Provides a new tab within the Insert Manager dialog, to add an anchor to one of the headings on the page.
=> Allow linking to heading anchors within editorial

Gemfile, Gemfile.lock, config/newrelic.yml
New Relic has already been set up for Contento within Puppet but the yaml config needs to be temporary left in this repo as we don't update Contento through Puppet for production.
=> Set up New Relic

config/environments/production.rb
In our current environment the same hostname is being used for both internal and external access to the CMS, by resolving the hostname to an internal or external IP depending on where it's being resolved from. To fix this, we need to allow the CMS to have a separate public hostname in the environment config.
=> Use public url for comfy if available.

app/models/page_mirror.rb, spec/models/page_mirror_spec.rb
all links inserted were previously hard coded to the page type of
articles. this now corretly looks up the page type for the link
=> link inserter uses correct url

app/models/redirect.rb, spec/models/redirect_spec.rb
this prevents hops eg.
/en/origin => /en/middle?param=a
/en/middle => /en/final
the above scenario above is not considered valid
as `middle` is considered a duplicate
=> redirects with parameters are considered as dupes

build.sh, test.sh
Newer versions of bundler create .bundle/config which is taking priority
over env var settings, BUNDLE_WITHOUT in particular. This breaks builds
when test.sh bundles without the "test" group and that state gets
saved. The fix, until Bundle 2 is released, is to rm the config file:
https://github.com/bundler/bundler/issues/3288
=> Fix builds with newer Bundler.

build.sh
So that we get RPM versions with the environment name built-in.
This shouldn't change anything for our normal Go pipelines as they all just use the value of `$GO_PIPELINE_COUNT`for `$GO_PIPELINE_LABEL` by default anyway. The `dev_test` and Azure build pipelines append something to the counter for those pipelines will generate RPMs with different names. This is desireable in Azure where we want more control over what RPMs we try to install (we only want the Azure-build ones), and probably makes sense for the `dev_test` ones too.
=> Build RPMs using the Go pipeline label.

Gemfile, Gemfile.lock
Bump mastalk version to 0.5.6, Updated mastalk gem pushed to rubygems,
relates to https://github.com/moneyadviceservice/mastalk/pull/9
=> [DEV APPROVED]Bump mastalk 0.5.5 to 0.5.6

Gemfile, Gemfile.lock
Bumping mastalk from version 0.5.7 to 0.5.8, Mastalk-0.5.8 gem pushed to rubygems
=> Bumping mastalk to 0.5.8

app/controllers/users_controller.rb, app/models/comfy/cms/user.rb, app/views/users/_form.html.haml, db/migrate/20160203094504_add_role_to_users.rb, db/migrate/20160203102911_migrate_users_to_have_role.rb, db/migrate/20160203104825_drop_admin_boolean_from_users.rb, db/schema.rb, features/step_definitions/user_management_steps.rb, features/support/world/cms.rb, spec/controllers/redirects_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/factories/users.rb, spec/models/comfy/cms/user_spec.rb
This is some ground work in preparation for adding a new 'External Editor' user to the application. We originally considered a separate `Role` model, but realised the following leads to a much simpler implementation.
* Adds `#role` to `Comfy::Cms::User` for helping with authorisation. The existing behaviour for regular and admin users has not been changed.
* Updates the user form to have a dropdown instead of a checkbox
* Data migration to move add the correct role to existing users
* Cleanup migration to remove the admin boolean from users table
=> [DEV APPROVED] Roles

app/models/comfy/cms/user.rb, features/step_definitions/user_management_steps.rb, features/user_management.feature, spec/models/comfy/cms/user_spec.rb
Using the groundwork laid in PR #300, a new editor role has been added.
The existing behaviour stating only admin users have access to the admin section has not been changed, therefore an editor does not have access to the user management page and only an admin can create a new editor user profile.
=> Add editor

app/assets/javascripts/comfortable_mexican_sofa/admin/modules/SearchBar.js
When browsing the application or running the cucumber tests, there is a warning:
```bash
"Collapsable" componentName was not found in the data-dough-component attribute
```
The reason this is occurring is that there is a component called `SearchBar`, which internally uses the `Collapsable` component.
To set up a dough component, there is typically an attribute on an HTML element like:
```html
<div data-dough-component="SearchBar">...</div>
```
However, when the Collapsable component is initialised within another component, it looks at the same HTML element's `data-dough-component` attribute to do a name check to make sure it's loading correctly. The check fails as it is effectively trying to match `"SearchBar"` to `"Collapsable"`. This change overrides the standard name for the …
=> [DEV APPROVED] Stop "Collapsable" componentName warning

db/seeds.rb, lib/cms/layout_builder.rb, lib/cms/page_builder.rb, spec/lib/cms/layout_builder_spec.rb, spec/lib/cms/page_builder_spec.rb
We've been looking at adding the ability to edit additional content on the frontend website. In the process of this, we had to run frontend locally against CMS locally. During this process, we encountered an issue where we were unable to load the website as there was no "Home Page" within contento.
Upon further investigation, we realised that in order for the frontpage of frontend to render, we needed to create a 'home_page' layout, and create a `Page` within contento with the slug 'the-money-advice-service', which uses this layout.
This PR adds to `seeds.rb` an additional snippet to generate the 'home_page' layout, and a very basic published homepage.
We were struggling with coming up with good names for the classes we've wrapped the behaviour in, also if anyone has any suggestions on …
=> Add home page seed

app/helpers/pages_helper.rb, app/models/page_register.rb, app/views/pages/_footer_bar.html.haml, app/views/pages/index.html.haml, features/delete_page.feature, features/home_page.feature, features/publish.feature, features/schedule.feature, features/step_definitions/edit_page_steps.rb, features/step_definitions/home_page_steps.rb, features/step_definitions/user_management_steps.rb, features/support/ui/pages/edit.rb, spec/helpers/pages_helper_spec.rb, spec/models/page_register_spec.rb
Previously we introduced the notion of an 'Editor' role into the cms. This PR is a continuation of that work to enforce the permitted abilities for an Editor.
* Removes ability to create a new page if current user is an editor
* Removes ability to schedule, publish, unpublish if current user is an editor
* Updated `PageRegister#save` to restrict editor capability.
=> [DEV APPROVED] Limit editor functionality

.env, Gemfile, Gemfile.lock, app/mailers/revision_mailer.rb, app/models/page_register.rb, app/views/revision_mailer/external_editor_change.html.erb, config/environments/production.rb, config/environments/test.rb, config/initializers/mailjet.rb, features/email_notification.feature, features/step_definitions/edit_page_steps.rb, features/support/ui/pages/edit.rb, spec/mailers/revision_mailer_spec.rb
This PR adds functionality for a notification email to be triggered whenever a user with an 'editor' role saves changes to content. We've added mailjet and reuse existing env vars from scripts.
=> [DEV APPROVED] Editors changing content should trigger a notification email

app/models/page_register.rb, spec/models/page_register_spec.rb
Users with an editor role, are able to make changes to pages, but not publish them.
We discovered whilst looking at QA test data, that we had missed one of the possible events (when a editor makes a draft version of an already published page).
This small PR addresses this issue.
=> editors should be able to create drafts from an existing published page

app/views/revision_mailer/external_editor_change.html.erb, spec/mailers/revision_mailer_spec.rb
Small PR. Switch email to use @page.label instead of @page.meta_title.
When an external editor saved changes to an English page, a link to the page was sent via email, however if changes were made to a Welsh page the link was not visible in the email as meta titles are not automatically copied across. Labels will always exist in both pages, so the label is a more appropriate attribute to use for the link in the email.
=> Use label instead of meta_title, as latter is not guaranteed to exist

app/models/page_register.rb, spec/models/page_register_spec.rb
There is an additional state where an Editor making changes to a page, should be able to save changes as a new draft.
To recap why we have 4 states here now:
* save_unsaved – Saving a new page which has been generated automatically, but no content exists.
* save_changes – We have a saved page which is unpublished, and changes are being saved
* save_changes_as_draft – There is a published page, and the user is saving a draft page.
* save_draft_changes – After creating a draft from a published page, the user can then save further changes to that draft.
=> Editors can ALSO save_changes_as_draft

db/seeds.rb, lib/cms/page_builder.rb, spec/lib/cms/page_builder_spec.rb
Now that we've updated the seeds.rb to generate a homepage, we've discovered an unexpected side effect...
Comfy weirdly defaults to the first layout used, which means if you've seeded a db from scratch, it now decides that the home_page layout should be the default, see gif:
This behaviour *only* happens when seeding a database from scratch.
This PR adds an example article into the database before adding the homepage, so it mimics the behaviour you would expect to see locally, or on a server with existing data like QA.
=> Force an article to exist before creating a homepage

app/models/page_register.rb, spec/models/page_register_spec.rb
Currently, editors are only able to save pages which are not published or scheduled. This change enables editors to save changes to pages that are already scheduled.
=> editors are allowed to alter scheduled pages

features/unschedule.feature
We’re struggling to pin down an issue with these passing on CI.
Marking wip to unblock the pipeline and will continue investigation separately.
=> Mark unschedule feature scenarios with @wip tag

Gemfile, Gemfile.lock
- Updated mastalk gem contains Azure CDN URL for cost calculator snippet (PR:https://github.com/moneyadviceservice/mastalk/pull/17)
- Mastalk 0.5.9 uploaded to rubygems
- Version already bumped in mastalk (PR:https://github.com/moneyadviceservice/mastalk/pull/18)
=> [DEV APPROVED] Bumping mastalk to 0.5.9

app/serializers/block_serializer.rb, app/views/pages/_form.html.haml, lib/cms/form_builder.rb, spec/lib/cms/form_builder_spec.rb, spec/serializers/block_serializer_spec.rb
It was discovered that the new publishing workflow fell down when trying to be used on non article type pages (home page, footer).  This PR addresses the issues and now they can be updated and scheduled in the same manner as articles.
The solution is a bit hacky, but that fits in perfectly with the way these forms are built.
=> 7222 fixes to scheduling functionality

app/views/pages/form_blocks/_footer.html.erb, lib/cms/layout_builder.rb, spec/lib/cms/layout_builder_spec.rb
Related to the task to [remove the newsletter signup from the footer in Frontend](https://github.com/moneyadviceservice/frontend/pull/1455) (PR) and [ticket 7333 in TP](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx?acid=E9844BE5A953DC8AF06B0B23D5B7DBA0#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==)
This must not be merged in before the [related frontend PR](https://github.com/moneyadviceservice/frontend/pull/1455)
Note: [Click here for the original PR which added the editable footer to the CMS](https://github.com/moneyadviceservice/cms/pull/318/files)
=> [DEV APPROVED] 7333 Removing editable footer newsletter

app/controllers/links/pages_controller.rb, app/presenters/page_mirror_presenter.rb, app/views/links/pages/_listing.html.haml, app/views/links/pages/_page_button.html.haml, features/link_to_article.feature, features/step_definitions/categories_steps.rb, features/step_definitions/edit_page_steps.rb, features/step_definitions/tags_steps.rb, features/support/env.rb, features/support/hooks.rb, features/support/ui/pages/edit.rb, features/support/world/cms.rb, features/support/world/helpers.rb, spec/presenters/page_mirror_presenter_spec.rb
The tests added here include a certain amount of refactoring to partially take out the reliance on a singleton object `cms_page`. This allows us to work with two pages in the same test, for example when linking to pages like in this change. The end goal should probably be to move the fixture generation into factory girl ... although that's probably for later change.
=> [DEV APPROVED]7228 link to mas bug

.env, config/initializers/comfortable_mexican_sofa.rb
This brings it in line with the name of other azure asset container
variables as defined in scripts.
=> [DEV APPROVED] Rename azure asset container env variable

package.json
This will fix for the users that do the fresh install for cms.
This will solve the annoying error:
```
$ ./node_modules/karma/bin/karma start spec/javascripts/karma.conf.js --single-run
cms/node_modules/di/lib/injector.js:9
throw error('No provider for "' + name + '"!');
^
Error: No provider for "framework:requirejs"! (Resolving: framework:requirejs)
```
=> Add requirejs and mocha to package.json

spec/javascripts/tests/EmbeddedGoogleAnalytics_spec.js
The Karma tests for DataCharts rely on checking properties of a JS object that is returned from the Google API - this object changes every few months. We are not testing a documented part of their API with these tests (nor are we actually checking that the DataChart is successfully created).
To be exact, we _could_ fix this right now by making this change:
from:
`expect(dataChart.Ka.chart.container).equal('some-chart-container');`
to:
`expect(dataChart.g$.chart.container).equal('some-chart-container');`
But that is merely pushing the problem on a few months until this happens again (see the commit history of this file). `g$` is not documented anywhere.
At the moment we can't get the CMS pipeline to run. So I'm suggesting we remove these tests, and write alternative ones that actually …
=> Removing bad Karma tests

lib/tasks/adhoc.rake
**Feature**
Added task `rake adhoc:extract_page` to create csv file for published articles and all their categories
=> [DEV APPROVED] 7674 - Extract a list of All articles and what categories they sit in

app/assets/javascripts/comfortable_mexican_sofa/admin/modules/scribe/scribe-plugin-linkeditor.js
When inserting an external link via the editor, if you do this without selecting some anchor text, the inserted kramdown markup appears over two lines/paragraphs.
This fixes that bug.
=> 7695 - Fix bug when inserting external link with no anchor text

config/environments/development.rb
* When you use a different port of CMS, the assets are not showed
anywhere. Removing this assets configuration solves the issue.
=> Fix issue of assets not being show in development

app/views/pages/index.html.haml, lib/permission_check.rb, spec/lib/permission_check_spec.rb
**Feature**
[card 7701](https://moneyadviceservice.tpondemand.com/entity/7701)
As a Welsh Translator, I need to be able to create and edit draft pages in Contento, so that I can create Welsh versions of pages and thus lighten the workload of the MAS internal content team.
**Proposed Solution**
=> [DEV APPROVED]Allow editor to create pages

app/assets/javascripts/comfortable_mexican_sofa/admin/modules/mastalk/snippets-model.js, app/models/content_composer.rb, app/models/table_captioner.rb, spec/models/content_composer_spec.rb, spec/models/table_captioner_spec.rb
Explored various different approaches and eventually went with leaving tables to be generated as normal, and adding a post processor to look for a paragraph with class of `caption` immediately after a table and if found add it as the `<caption>` tag.
Adding a class to a paragraph is done like so:
```
A paragraph of text
{: .a-class-to-apply}
```
The javascript table insert snippet has been updated to include the caption paragraph.
I ran the styling past @slaywell and we ended up with leave it as it was as it appears that the styling had already been considered in the past.
=> 7686 - A11Y - a way to add captions to tables

.env, app/controllers/api/page_feedbacks_controller.rb, app/controllers/page_feedbacks_controller.rb, app/filters/api/authentication_filter.rb, spec/controllers/api/page_feedbacks_controller_spec.rb
Background:
On the development of this feature it was added one endpoint with two HTTP verbs on CMS API:
POST   "/api/en/example-article/page_feedbacks"
PATCH "/api/en/example-article/page_feedbacks"
The problem that the CMS API is public and doesn't have any authentication mechanisms, so anybody malicious can create a script to just create a lot of likes and dislikes for each article if they want it. So adding an authentication solves the problem.
=> [DEV APPROVED] - 7711 protect cms endpoints

app/models/internal_link.rb, spec/models/internal_link_spec.rb
**Bug**
[Card 7812](https://moneyadviceservice.tpondemand.com/entity/7812)
Improve punctuation mark exclusion list for id attribute for article h2 tags
=> [DEV APPROVED] - [7812] Internal Links menu

app/controllers/categories_controller.rb, app/controllers/clumps_controller.rb, app/models/clump.rb, app/models/clumping.rb, app/models/comfy/cms/category.rb, app/views/categories/show.html.haml, app/views/clumps/index.html.haml, app/views/clumps/new.html.haml, app/views/clumps/show.html.haml, config/locales/clumps.yml, config/routes.rb, spec/controllers/clumps_controller_spec.rb, spec/factories/clumpings.rb, spec/factories/clumps.rb, spec/models/clump_spec.rb, spec/models/clumping_spec.rb, spec/models/comfy/cms/category_spec.rb
This ticket is being split off into two tickets. It originally was for adding an interface for editing aspects of the clumps including the tool links, however we still need to do some backend work for those tool links, that portion is being put into a new ticket.  This PR now solely deals with adding some interface for the parts of the clumps which already exists (titles, descriptions, categories).
The interface I've implemented here largely mirrors that of the categories.
We can create, edit and reorder clumps (but, like with categories, not delete them).
We can reorder the categories in the clumps via the category#show page.
We can (un)assign categories to clumps via the category#edit page.
=> 7758 - initial clump administration

Gemfile, Gemfile.lock, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/MASEditor.js, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/mastalk/snippets-model.js, app/views/comfy/admin/cms/pages/_toolbar.haml
This is part of a collection of 4 pull requests across 4 repos, concerning the **'Callout'** module that we have within most articles:
### Linked PRs:
- [Frontend - 7757 - Adding icon for Tool callout box](https://github.com/moneyadviceservice/frontend/pull/1612)
- [Yeast - 7757 - New styles for Callout module](https://github.com/moneyadviceservice/yeast/pull/24)
- [MASTALK - 7757- New callout tool snippet](https://github.com/moneyadviceservice/mastalk/pull/21)
- Restyling the default Callout module to use the turquoise style below
- Adding a new 'Tools' Callout module that can be used by editors to differentiate our Tools from different types of content
...Adds the new MASTalk snippet to the CMS so that editors can insert it.
=> [DEV APPROVED] Adding new snippet to CMS for Tools Callout

app/controllers/clumps_controller.rb, app/models/clump.rb, app/models/clump_link.rb, app/serializers/clump_link_serializer.rb, app/serializers/clump_serializer.rb, app/views/clumps/_link_fields.html.haml, app/views/clumps/new.html.haml, app/views/clumps/show.html.haml, db/migrate/20161207123802_create_clump_links.rb, db/migrate/20161208151020_create_links_for_existing_clumps.rb, db/schema.rb, spec/models/clump_link_spec.rb
Had a few false starts on this, trying a few different approaches to try and avoid having such a similar model to the existing `Link` model but ended up just going with just that.
The spec for this requires that we can have up to four links in a clump, so in order to simplify the interface we just build four of these when you create a clump and then the interface allows you to edit these but not add or remove any.  Validation allows you to either leave some blank or requires you to populate them entirely, and when rendering the json we  only show the complete ones.
I tried various approaches to reuse the existing model but it wasn't suitable for STI (the subclass of Link would have to remove the validation applied in the parent) and when I tried adding conditionals based on the `linkable` …
=> 7831 - (tool) links in clumps

app/serializers/clump_serializer.rb
Picked up on and fixed while working on that ticket 7747 (plumb the api into the frontend interface).
Wasn't defining the scope (locale) properly when instantiating the `ClumpLinkSeralizer` from `ClumpSerializer`, this fixes that.
=> [DEV APPROVED] - Fix bug in defining ClumpLinkSerializer scope

db/migrate/20170110153128_create_extra_clump_links.rb, db/schema.rb
Rather than add validation on the number of links a clump can have (which would have been a more complex UX addition) we went with creating a fixed number of empty links in the db and then showing them based on whether or not they were complete.
This approach wasn't finalised when the migration to create the initial clumps was created, so this adds the missing empty ones so that all clumps have four each.
=> Add migration to create extra empty clump links

db/migrate/20170112102402_retirement_clump_extras.rb, db/schema.rb
I rushed the PR to create the new Retirement clump and unfortunately forgot to consider the clump links.
The migration in this PR moves retirement related links over to the Retirement clump and then creates extra empty ones so that both the old and new clumps have four each.
=> Clump link changes to go with the new ‘Retirement’ clump

Gemfile, Gemfile.lock, app/controllers/api/content_controller.rb, app/models/alternate_page_blocks_register.rb, app/models/alternate_page_blocks_retriever.rb, app/models/blocks_retriever.rb, app/models/page_blocks_register.rb, app/models/page_blocks_retriever.rb, app/models/page_content_register.rb, app/serializers/block_serializer.rb, db/migrate/20161229133318_add_processed_content_to_comfy_cms_blocks.rb, db/schema.rb, lib/tasks/page_conversion.rake, spec/factories/revisions.rb, spec/models/alternate_page_blocks_register_spec.rb, spec/models/alternate_page_blocks_remover_spec.rb, spec/models/page_content_register_spec.rb
Webfeeds request to the CMS on `/en/articles/published` and it takes almost 2 minutes to finish the whole request. You can see on TP as 7833.
Further investigation were found that there was a lot of N+1 queries and a lot of markdown processing to html. Detailed explanation is below.
So removing the n+1 queries and add a 'sort of cache' (convert the html only when you save the page and not when you request the page) will solve half of the problem.
These are the tasks to complete related to this PR:
*This will affect all apps that are using the CMS (the site and the webfeeds and probably universal credit).*
This PR is waiting for two PR's to be merged. After the merge I will address on the Gemfile: 
- https://github.com/moneyadviceservice/comfortable-mexican-sofa/pull/24
- …
=> [DEV APPROVED] Speed up CMS article requests

app/assets/javascripts/comfortable_mexican_sofa/admin/modules/StickyElements.js, app/assets/javascripts/require_config.js.erb, app/assets/stylesheets/comfortable_mexican_sofa/admin/application.css.scss, app/assets/stylesheets/comfortable_mexican_sofa/admin/helpers/_fixedsticky.scss, app/views/pages/_form_title.html.haml, bower.json.erb
**Description**
Currently the editor toolbar is floating over the content of the page rather than being fixed at the top, also the background isnt showing:
On further investigation I found that we are using the CSS property ``position: sticky`` and a fallback javascript plugin [filament-sticky](https://github.com/filamentgroup/fixed-sticky) AS this is still not supported by IE at all.  We are also using a custom dough component that initiates the plugin.
In order to make this as simple as possible I decided to remove the 3rd party plugin (As this seems to have stopped working anyway) and update the component to do to work of applying a position: fixed property, rather than trying to use position: sticky, then trying to patch in a fix for unsupported browsers.
To give a bit of perspective …
=> [DEV APPROVED]7995 - Floating Toolbar bug

README.md
In order to use a local instance of this for development we need content. The suggestion to clone the QA database is in the Wiki, but it is not obvious that we need to look there when following setup instructions in the `frontend` and `cms` READMEs.
I am not 100% sure about including the instructions in this public repository, but there are references to other private servers in the `frontend` README.
(I also noticed a reference to `gems.test.mas` here, which I've taken out.
=> Mention cloning QA database and other tidy-ups

app/models/comfy/cms/page.rb, lib/clock.rb, lib/cms/publish_scheduled_pages_task.rb, spec/lib/cms/publish_scheduled_pages_task_spec.rb, spec/models/comfy/cms/page_spec.rb
This pr sets a published date of a page to be when its scheduled to be released.
The CMS app is not revising the published_at date on articles with scheduled revisions upon publication, although the content is updated, the published_at date is required by the web feeds management system to update partners on update articles in their feeds.
[TP link](https://moneyadviceservice.tpondemand.com/restui/board.aspx?acid=13857292912bd09b911bf771e091f219#page=bug/8198)
=> [DEV APPROVED] -8198 - Set published date for scheduled posts

app/controllers/categories_controller.rb, app/views/categories/show.html.haml, features/categories_admin.feature, features/step_definitions/categories_admin_page_steps.rb, features/support/env.rb, features/support/hooks.rb, features/support/ui/pages/categories_admin.rb, features/support/ui/pages/category_details.rb
This pr addresses [TP8603](https://moneyadviceservice.tpondemand.com/restui/board.aspx?acid=ddd7f3a626844ab8d1bee3f06ec28efa#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&boardPopup=bug/8603).  A user design flaw in production allows a content editor or admin user to assign a category as the parent category to itself. If the user then tries to view that category page, he'll experience a timeout. Technically, the cause is an infinite loop in the code.
The short term approach is to disable a category from being selected as its own parent in the drop down list on the form for editing categories. A better approach is to validate the parent category when the form is submitted. This latter approach needs to be prioritised. In the interim, …
=> [DEV APPROVED] 8603 Disable category from being selected as the parent

db/seeds/fincap.seeds.rb
**This is a support work** for [8912](https://moneyadviceservice.tpondemand.com/entity/8912-add-grouped-blocks-to-cms-insights) and [9001](https://moneyadviceservice.tpondemand.com/entity/9001-cms-api-find-all-insight-documents)
Enhance seed data to:
* include topics and client_groups fields 
* give all pages a state of "published", because the cms api only retrieves 'published' pages
This data will help implement the first part of the evidence hub i.e. building the Insight pages
=> [DEV APPROVED] Add more data to fincap seeds and publish those pages

app/helpers/pages_helper.rb, app/views/pages/form_blocks/_insight.html.haml, features/pages_form/fincap_insight_pages.feature, features/step_definitions/fincap_pages_steps.rb, features/support/ui/pages/edit.rb, lib/cms/form_builder.rb, lib/cms/layout_field.rb, lib/tasks/fincap.rake, spec/lib/cms/layout_field_spec.rb
[TP8913](https://moneyadviceservice.tpondemand.com/entity/8913-add-text-blocks-to-cms-insights)
Add insight template
Add cucumber feature
Add refactored code for insight partial
Add fields to template!
**refactoring form builder**
The method `default_tag_field` needs to be refactored to be maintainable. Although we have updated some of this method to work a little better we have opted not to refactor this whole method yet. This is down to the fact that we know we will have to do more work to this method with the addition of multiple blocks (checkboxes etc.). It may be unwise to refactor this code before that point as it may make it harder to then apply any new changes from that point. _Therefore_ we will address the refactor of this method in that PR …
=> [DEV APPROVED] 8913 add text fields

app/controllers/api/documents_controller.rb, spec/controllers/api/documents_controller_spec.rb, spec/factories/blocks.rb, spec/factories/pages.rb
[TP 8997](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5580782241563718174&appConfig=eyJhY2lkIjoiRTQ4MDEyNENDOUYxRDU4RDg0RTEyRjNCODBEN0VBMUYifQ==&searchPopup=userstory/8997)
Uses the `keyword` parameter from the request to search page content and return an array of documents which contain the `keyword`
The [Comfortable Mexican Sofa gem](https://github.com/moneyadviceservice/comfortable-mexican-sofa) provides scopes which the api can use for cleaner looking queries. We've used the [with_content_like](https://github.com/moneyadviceservice/comfortable-mexican-sofa/blob/master/app/models/comfy/cms/page.rb#L104) scope to implement the keyword search.
1. Search title
2. Search overview
=> [DEV APPROVED] 8997 API Search by keyword - Insight

Gemfile, Gemfile.lock, README.md, app/controllers/api/category_contents_controller.rb, app/controllers/api/content_controller.rb, app/controllers/api/documents_controller.rb, config/initializers/apipie.rb, config/routes.rb, spec/controllers/api/documents_controller_spec.rb
This pr explores one option for documenting the cms api, namely using [Apipie](https://github.com/Apipie/apipie-rails).
Documentation for some of the api methods has been included as an example. This approach is open for discussion and is merely a response to a request to look into how we document the cms api.
=> Document api with Apipie

app/controllers/api/content_controller.rb
Addresses an error from the apipie gem - specifically the parameter for the route is optional and was incorrectly set to required [when the apipie gem was originally implemented](https://github.com/moneyadviceservice/cms/pull/406).
=> [DEV APPROVED] apipie param is not required

app/controllers/api/documents_controller.rb, spec/controllers/api/documents_controller_spec.rb, spec/factories/blocks.rb, spec/factories/pages.rb
[TP 8997](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5580782241563718174&appConfig=eyJhY2lkIjoiRTQ4MDEyNENDOUYxRDU4RDg0RTEyRjNCODBEN0VBMUYifQ==&searchPopup=userstory/8997)
This pr adds searching through page titles for a given keyword.
The query needs to return pages where the keyword is in the title OR the content. Since chaining scopes only works for 'AND' search queries, it is necessary to use the more wordy `where` syntax.
1. Search only blocks which are 'content' or 'overview'
2. Refactor the documents_controller#filter_documents method
=> 8997 API: Search page titles for search term

app/controllers/api/documents_controller.rb, spec/controllers/api/documents_controller_spec.rb, spec/factories/blocks.rb, spec/factories/pages.rb
[TP 8997](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5580782241563718174&appConfig=eyJhY2lkIjoiRTQ4MDEyNENDOUYxRDU4RDg0RTEyRjNCODBEN0VBMUYifQ==&searchPopup=userstory/8997)
This pr addresses part of the 4th expectation in the user story, namely performing the search on the **content** or the **overview** blocks of a page.
PRs #410 and #405 address the other parts of the story.
=> [Dev Approved] Only search content or overview blocks

app/controllers/api/documents_controller.rb, spec/controllers/api/documents_controller_spec.rb, spec/factories/blocks.rb, spec/factories/pages.rb
Fix for a bug in the search which was returning a page twice if the keyword was found in the title and the content block. By adding the `uniq` qualify we ensure that a page is only returned once.
=> modify query to select distinct pages

app/controllers/api/category_contents_controller.rb
This pr fixes a bug initiated by installing a gem to facilitate documenting the cms api. 
Specifically the categories controller takes a parameter which is of type `string` and the documentation had been set to `number`. Hence an error was generated when the category api was invoked with a string. This pr changes the parameter type to be `string`.
=> Amend parameter type for categories api

Gemfile, Gemfile.lock, app/controllers/api/documents_controller.rb, app/filters/document_provider.rb, spec/controllers/api/documents_controller_spec.rb, spec/factories/blocks.rb, spec/factories/pages.rb, spec/filters/document_provider_spec.rb
[TP 8999](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=userstory/8794&searchPopup=userstory/8999)
This pr adds filtering to the search. It takes an optional `blocks` parameter formatted as an array of hashes e.g.
`[{identifier: 'client_group', value: 'Working age (18 - 65)'}] `
The search query is complex so it has been moved out of the controller into a class solely responsible for retrieving the documents.
I added brakeman to the gemfile to test that the sql query is secure. 
NEXT STEP
=> TP 8999 api search filtering

app/controllers/api/documents_controller.rb
[TP 8774](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5580782241563718174&appConfig=eyJhY2lkIjoiRTQ4MDEyNENDOUYxRDU4RDg0RTEyRjNCODBEN0VBMUYifQ==&searchPopup=userstory/8774)
As part of the mysql query to search for documents which contain only the blocks which meet the filter conditions, we use a complex subquery. The mysql SELECT COUNT function to determine the number of documents returned by the complex subquery is failing with a mysql syntax error. This pr provides a short term fix by using the ruby method 'size'. 
This issue will be revisited as part of [TP 9000](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5580782241563718174&appConfig=eyJhY2lkIjoiRTQ4MDEyNENDOUYxRDU4RDg0RTEyRjNCODBEN0VBMUYifQ==&boardPopup=userstory/9000/silent), …
=> [DEV APPROVED] Broken mysql query

config/schedule.rb, lib/clock.rb
We currently scheduling the Algolia search index rake task using clockwork gem. In the production environment this is causing an issue as the rake task is running on all of the instances of CMS hosts, which is using double to amount of our indexing quota.
To overcome this we will be migrating the scheduling of the rake task to whenever gem - https://github.com/javan/whenever
This will give us the ability to add the task to crontab on a per host basis, enabling us to run the index only once.
=> Migrate search index task from clockwork to whenever gem

config/schedule.rb
To keep within our index operations quota on Algolia, we need to run the cron job every four days. The job will run on the 21st, 25th and 29th.
Following this we will return to a daily schedule.
https://moneyadviceservice.tpondemand.com/entity/9154-migrate-algolia-indexing-from-clockwork-to
=> Update cron schedule for search:index to stay within quota

app/assets/javascripts/comfortable_mexican_sofa/admin/modules/MASEditor.js, app/assets/javascripts/comfortable_mexican_sofa/admin/modules/mastalk/snippets-model.js, app/views/comfy/admin/cms/pages/_toolbar.haml
TP Ticket [9128](https://moneyadviceservice.tpondemand.com/entity/9128-primary-button-snippet)
This PR adds the fincap button to the list of snippets:
[The associated mastalk PR can be found here](https://github.com/moneyadviceservice/mastalk/pull/24)
Screenshot of component rendered in fincap frontend
=> 9128 fincap button snippet

app/controllers/api/documents_controller.rb, app/filters/document_provider.rb, spec/controllers/api/documents_controller_spec.rb, spec/filters/document_provider_spec.rb, spec/requests/documents_spec.rb
[TP 9090 ](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5580782241563718174&appConfig=eyJhY2lkIjoiRTQ4MDEyNENDOUYxRDU4RDg0RTEyRjNCODBEN0VBMUYifQ==&searchPopup=userstory/9090)
It is technically possible to provide an unlimited number of filters which would affect the database query since each filter generates a subquery. This pr limits the number of subqueries generated to 26. Refer to the TP card as to why its limited to 26.
=> TP 9090 Only allow a maximum of 26 filters as part of the API request

Gemfile, Gemfile.lock, bin/rake, features/index_database.rake, features/step_definitions/indexing_steps.rb, features/support/env.rb
[TP card](https://moneyadviceservice.tpondemand.com/entity/9095-cms-add-feature-tests-for-indexing)
We are missing feature tests to check the proper indexing of our pages from our CMS system.  
This PR provides feature tests to make sure we are sending the right objects to be indexed on the site search.
Since the indexing is performed by command line rake tasks, I added the [aruba gem](https://github.com/cucumber/aruba) which adds feature tests for command line apps. 
To make this approach work, I needed to force an environment variable option which I set to the `local` adapter because we don't want to index anything to Algolia on our feature tests.
Aruba clashes with Spring because aruba uses the tmp directory to run the CLI interface and Spring needs to be in the Rails root directory. …
=> [DEV APPROVED] Add feature tests for indexing cms database

db/seeds/fincap.seeds.rb, features/pages_form/fincap_insight_pages.feature, features/step_definitions/fincap_pages_steps.rb, features/support/ui/pages/edit.rb, lib/tasks/fincap.rake
[TP Task 9179](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiQjRGMUI3NDVDQTgzMEM3QzQ2MDBCNjExRTUxMTQ4OEIifQ==&searchPopup=userstory/9167)
An insight page can present evidence which is qualitative or quantitative or both. The cms new page form needs to include checkboxes for the editor to indicate which type of evidence the page is.
The processing of these checkboxes is completed as part of another pr. This pr amends the attribute name from `data_type` to `data_types` and adds feature test for the ui aspect of creating/editing.
=> [DEV APPROVED] - 9179 Amend cms page form to accept data_types attribute

app/views/pages/_form.html.haml, config/locales/pages.yml, db/migrate/20180427145114_add_meta_keywords_to_comfy_cms_pages.rb, db/schema.rb, lib/cms/indexers/page.rb, spec/lib/cms/indexers/page_spec.rb
[TP card](https://moneyadviceservice.tpondemand.com/entity/9144-site-search-enhancement-add-meta-keywords)
The Site Search product, Algolia, is working on the site but we are limited in the tools we need in order to influence search results. 
Currently Algolia indexes pages on page title and meta-description.
We could edit meta descriptions in order to help fix searches with missing results, and to help influence what appears towards the top of the results. However, the problem with this is that Meta description is used on Google SERPs, and generally full sentences are better than keyword stuffing for these.
So adding a field to add those keywords makes the site search flexible for the Digital team to influence the search results.
So with the solution, I added a field called meta keywords …
=> [DEV APPROVED] Add meta keywords field to site search index

app/serializers/block_serializer.rb, spec/serializers/block_serializer_spec.rb
Before this PR, given we had the following blocks:
```
<Comfy::Cms::Block id: 13, identifier: "topics", content: "Saving",
blockable_id: 2, blockable_type: "Comfy::Cms::Page">
<Comfy::Cms::Block id: 14, identifier: "topics", content: "Financial
Capability", blockable_id: 2, blockable_type: "Comfy::Cms::Page">
```
**Then the API were return two topics but with duplicated "Saving" as value.**:
```
{
"identifier": "topics",
"content": "<p>Saving</p>
",
"created_at": "2018-05-10T14:26:47.000Z",
"updated_at": "2018-05-10T14:26:47.000Z"
},
{
"identifier": "topics",
"content": "<p>Saving</p>
",
"created_at": "2018-05-10T14:26:47.000Z",
"updated_at": "2018-05-10T14:26:47.000Z"
},
```
This was returning duplicated values because the Block retriever class was using Array#find for all blocks even …
=> Allow block collection to return all values

app/controllers/api/documents_controller.rb, spec/controllers/api/documents_controller_spec.rb
[TP card](https://moneyadviceservice.tpondemand.com/entity/9000-cms-api-search-pagination)
This PRs adds pagination to the CMS API.
So now you can pass the page parameter:
`http://localhost:3000/api/en/documents.json?page=1`
And more information will be provided on the meta key:
```
"meta": {
"results": 5,
"page": 1,
"per_page": 20,
"total_pages": 1
}
```
=> Add pagination to API /documents

spec/lib/cms/form_builder_spec.rb
This error came about from our refactor for form_builder 
https://github.com/moneyadviceservice/cms/blob/fincap/lib/cms/form_builder.rb#L112
blocks_attributes should be an array of hashes, but in the test it was just a hash that was passed in.
=> Fix broken test

app/controllers/api/documents_controller.rb, db/seeds/fincap.seeds.rb, spec/controllers/api/documents_controller_spec.rb, spec/requests/documents_spec.rb
There was a test that was failing on fincap because there was an insight page without year of publication. It was there but maybe it was deleted by accident. This PR addresses this fix.
Other thing that I address on this PR is adding authentication to the Documents API. This route is starting to become very important. It sounds safe to me to add a token auth to it.
I also found that the documents API has two files as requests spec. One living in the controller dir and another on the request dir. I don't know why is that so but I prefer to leave as it is for now and ask @margOnline the reason about it when she is back.
=> Feature/9000 - add authentication to the documents API

app/controllers/api/documents_controller.rb, app/filters/document_provider.rb, db/seeds/fincap.seeds.rb, spec/controllers/api/documents_controller_spec.rb, spec/factories/pages.rb, spec/factories/tags.rb, spec/filters/document_provider_spec.rb
[TP card](https://moneyadviceservice.tpondemand.com/entity/9205-thematic-reviews-content-association)
This PR addresses the search through pages by tag.
Allowing the documents API  to search by tag means that on CMS we can search all summaries that are within a tag. The tag will be associated with a Thematic review because the name of the tag and the name of the slug are the same.
Given that I have the thematic review:
```
Type: Thematic Review
Slug: my-awesome-thematic-review-page
```
and an Insight:
```
Type: Insight
slug: some-insight
tag: my-awesome-thematic-review-page
```
Note that the Insight above  **should** have a tag with the same name as the thematic review's slug.
When we search for the tag "my-awesome-thematic-review-page", the pages which have this tag will be returned. On …
=> 9205 - Thematic review

db/seeds/fincap.seeds.rb
This PR adds more tags to the evidence summaries.
This makes the tests more robust since on the fincap we need to display summaries and filter them.
=> Add more tags to evidence summaries

config/routes.rb
[TP 9202](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5580782241563718174&appConfig=eyJhY2lkIjoiRTQ4MDEyNENDOUYxRDU4RDg0RTEyRjNCODBEN0VBMUYifQ==&searchPopup=userstory/9202)
There is a requirement for Fincap to have a page which shows summaries of all the thematic reviews.
[Related fin_cap pr](https://github.com/moneyadviceservice/fin_cap/pull/143)
We need a new route for thematic_reviews because another route matched the thematic_reviews request via the `:page_type` parameter and was sending it to `contents_controller#show`. 
The new route makes use of `documents_controller#index` because in fin_cap when we call this new route we give it a `:page_type` parameter.
=> Route for thematic_reviews

config/routes.rb, db/seeds/fincap.seeds.rb, lib/tasks/fincap.rake
[TP 9202](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5580782241563718174&appConfig=eyJhY2lkIjoiRTQ4MDEyNENDOUYxRDU4RDg0RTEyRjNCODBEN0VBMUYifQ==&searchPopup=userstory/9202)
There is a requirement for Fincap to have a page which shows summaries of all the thematic reviews.
- new route for thematic_reviews_landing_page
- add hero image and hero description components for thematic_reviews_landing_page
[Related fin_cap pr](https://github.com/moneyadviceservice/fin_cap/pull/143)
We need a new route for thematic_reviews_landing_page because another route matched the thematic_reviews_landing_page request via the `:page_type` parameter and was sending it to `contents_controller#show`. 
The new route makes use of `documents_controller#index` because in fin_cap when we …
=> thematic_reviews_landing_page route

app/filters/document_provider.rb, spec/filters/document_provider_spec.rb
[TP 8761](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5580782241563718174&appConfig=eyJhY2lkIjoiRTQ4MDEyNENDOUYxRDU4RDg0RTEyRjNCODBEN0VBMUYifQ==&boardPopup=userstory/8761/silent)
Summaries should be displayed in descending order of creation date, in other words, most recently created. Creation date is used for ordering to ensure summaries created months ago but **edited** more recently do not edge out more recently **created** summaries.
=> Return evidence summaries in descending order of creation date

app/assets/javascripts/comfortable_mexican_sofa/admin/modules/ArticleComponents.js, app/assets/javascripts/require_config.js.erb, app/assets/stylesheets/comfortable_mexican_sofa/admin/components/_article_component.scss, app/assets/stylesheets/comfortable_mexican_sofa/admin/components/_editor.scss, app/assets/stylesheets/comfortable_mexican_sofa/admin/layout/_editor.scss, app/assets/stylesheets/comfortable_mexican_sofa/admin/lib/_variables.scss, app/helpers/pages_helper.rb, app/views/pages/form_blocks/_article.html.haml, spec/javascripts/fixtures/ArticleComponents.html, spec/javascripts/test-main.js, spec/javascripts/tests/ArticleComponents_spec.js
[TP9155](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=userstory/9155)
This work is to enhance the CMS to make it more user-friendly when adding/editing article pages. Currently the inputs for the components (hero image, CTA list etc.) are displayed at the bottom of the page: 
This PR changes the layout a little to display them at the side of the main editor and makes them fully visible only when there is content already saved or the editor wishes to add some new content: 
Could probably benefit from some more consideration to the look and feel though.
=> [DEV APPROVED] 9155 cms article component

app/views/pages/form_blocks/_news.html.haml, db/seeds/fincap.seeds.rb, features/pages_form/fincap_news_pages.feature, features/pages_form/fincap_review_pages.feature, features/preview.feature, features/step_definitions/edit_page_steps.rb, features/step_definitions/fincap_background_steps.rb, features/step_definitions/fincap_pages_steps.rb, features/support/ui/pages/edit.rb, lib/cms/form_builder.rb, lib/comfortable_mexican_sofa/extensions/tag.rb, lib/tasks/fincap.rake
[TP 9118](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5580782241563718174&appConfig=eyJhY2lkIjoiRTQ4MDEyNENDOUYxRDU4RDg0RTEyRjNCODBEN0VBMUYifQ==&searchPopup=userstory/9118)
There is a fincap requirement for editors to be able to add news pages. These pages are similar to articles but include a date which enables the editors to fine tune the order in which news items are displayed on the Latest News page. [Related TP story, 9117](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5580782241563718174&appConfig=eyJhY2lkIjoiRTQ4MDEyNENDOUYxRDU4RDg0RTEyRjNCODBEN0VBMUYifQ==&searchPopup=userstory/9117)
=> 9118 news page layout

app/controllers/api/documents_controller.rb
[TP 9281](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5580782241563718174&appConfig=eyJhY2lkIjoiRTQ4MDEyNENDOUYxRDU4RDg0RTEyRjNCODBEN0VBMUYifQ==&searchPopup=userstory/9281)
This pr addresses the technical debt on fincap where filtering the evidence hub search by Year of Publication was returning incorrect results.
The `value` parameter was being permitted as a string which worked for the other filters. Year of Publication values are passed as an array and therefore were being rejected.  Allowing the `value` to be a string OR an array satisfies all filters.
Please see [associated fincap pr 158](https://github.com/moneyadviceservice/fin_cap/pull/158) for testing.
=> Allow block filter values to be strings or arrays

app/filters/document_provider.rb, spec/factories/blocks.rb, spec/factories/pages.rb, spec/filters/document_provider_spec.rb
[TP 9305](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5580782241563718174&appConfig=eyJhY2lkIjoiRTQ4MDEyNENDOUYxRDU4RDg0RTEyRjNCODBEN0VBMUYifQ==&searchPopup=task/9305)
On the fincap latest news page, there needs to be links to allow the user to view news items from a particular year. This pr amends the database querying to ensure pages are only returned for a specific year.
Refer to [fin_cap pr 155](https://github.com/moneyadviceservice/fin_cap/pull/155).
Several solutions were considered to meet the requirement. This solution was considered the simplest.
Fincap news article pages include an `order_by_date` which is considered the 'official publication' date and is specifically used by editors to manipulate the order in which these articles appear on the …
=> Amend searching by keyword

app/controllers/api/documents_controller.rb, app/serializers/page_serializer.rb, db/seeds/fincap.seeds.rb, spec/serializers/page_serializer_spec.rb
[TP 9283](https://moneyadviceservice.tpondemand.com/restui/board.aspx#page=board/5481321774608038243&appConfig=eyJhY2lkIjoiNjRGM0FCMDY3RUQ5MDREM0RGNDZGOUM0REZENUZBMzIifQ==&searchPopup=userstory/9283)
A number of FinCap pages need to show related news articles. Related news articles are those that have the same tags as the current page.
Ensure keywords are included in the json response that cms returns to fincap:
- Add tags method to the page serializer to return an array of values.
- Ensure api documentation allows tag parameter to be a string or an array.
This solution works with [changes to mas-cms-client](https://github.com/moneyadviceservice/mas-cms-client/pull/31)
=> [DEV APPROVED] 9283 Latest news component

lib/prismic/cms_converter.rb, lib/prismic/converted_document.rb, lib/prismic/data_store.rb, lib/prismic/document.rb, lib/prismic/fragment.rb, lib/prismic/html_converter.rb, lib/prismic/migrator/article.rb, lib/prismic/migrator/base.rb, lib/prismic/tag_converter.rb, lib/tasks/prismic.rake, spec/lib/prismic/cms_converter_spec.rb, spec/lib/prismic/converted_document_spec.rb, spec/lib/prismic/document_spec.rb
[TP card](https://moneyadviceservice.tpondemand.com/entity/8847-convert-prismic-json-data-into-markdown)
So this PR address the **ground work** to migrate all Prismic documents into CMS.
The basic strategy for the implementation:
1) Convert Prismic format into **html** and **markdown**
2) Migrate over to the CMS database (using html and markdown version)
Note: There are some aspects of the code which should be better but since this code will be used only once, I decided to keep as is and skip some refactor steps.
To create the migration for each page type on prismic you need to:
1) Create a class under Prismic::Migrator namespace with the same class name as the type name of prismic.
2) Implement #layout_identifier which is the same layout identifier on the database to link the page with …
=> [DEV APPROVED] Feature/8847 fincap migration

features/step_definitions/fincap_background_steps.rb, lib/tasks/fincap.rake
This pr addresses an issue on whereby thematic reviews and the thematic review landing page is not being shown. 
The cms is returning a '404 not found' error for these pages because they were set up using hyphens for their page layout identifier. Therefore the cms is looking for documents by page type equal to `thematic-review` and should be looking for `thematic_review`.
Amend the page layout identifier to use underscores instead of hyphens.
=> Amend page layout identifiers

.env-example, README.md, app/filters/api/authentication_filter.rb, bin/setup, config/application.rb, config/database.yml, config/environments/production.rb, config/initializers/algolia_setup.rb, config/initializers/comfortable_mexican_sofa.rb, config/initializers/domain.rb, test.sh
[TP9299](https://moneyadviceservice.tpondemand.com/entity/9299-deploy-fincap-cms-to-production-environment)
The main part of this work is to set the correct ENV variables depending on which application domain should be running (MAS or FINCAP)
Most of this work is done within the new `domain.rb`
At the moment `domain.rb` has both the object Domain and the config script at the bottom of it. Probably makes sense to split this out, but I haven't yet decided how best to do this and where to put the files in the tree. It needs to be loaded and run before most of the application so things like the database know's it's name (hence why it's loaded into the Application [here](https://github.com/moneyadviceservice/cms/pull/459/files#diff-b1fe55db50c712fef0673345e5b9c0d9R14))...however the current …
=> Fincap 9299 deployment strategy

test.sh
This is not required in the test script as will be removed. The environement vars are passed in Go during testing and build
=> remove APP_NAME env var from test script

lib/cms/form_builder.rb
On prismic migration there were some fields that were not there. So since the code assumption was to the blocks always be there then the code broke.
So making the code flexible to accept blank fields solves the issue.
=> Fix bug when evidence hub does not have any content

db/seeds/fincap_data/homepage_seeds.rb, db/seeds/fincap_data/lifestage.seeds.rb, db/seeds/fincap_data/regional_strategy_seeds.rb, features/step_definitions/fincap_background_steps.rb, lib/tasks/fincap.rake
The title for the teaser section with the 3 teaser boxes is not displaying. 
There are 2 solutions to fixing the issue of the teaser_section_title
not displaying:
1. change the field to be a simple text field and not a component
2. update the identifier that the article_template is looking for in fincap
I chose the first approach because it made more sense that this field be a simple text field since the content will only ever be a few words of text.
=> [DEV APPROVED] Fix for  teaser_section_title not displaying on Fincap

config/initializers/domain.rb, lib/rack/redirect_middleware.rb
[TP card](https://moneyadviceservice.tpondemand.com/entity/9225-implement-internal-redirect-feature-on-fincap)
Fincap uat was redirecting to the MAS site. One example you can see https://fincap-cms.uat.dev.mas.local/api/en/evaluations/evaluation-of-my-money-now
Mas CMS redirects should redirect to MAS site.
Fincap CMS redirects should redirect to Fincap site.
There was an env var hard coded on redirect middleware which uses as the domain to be redirect to.
Make the domain to look for the right APP_NAME makes the redirect work as expected to.
The env var that's being used  in MAS site is called FARADAY_HOST. I think is a terrible name but I decided to leave as it is to not break functionality under the MAS site.
There is an env var on production already called FINCAP_PUBLIC_WEBSITE_DOMAIN. …
=> [DEV APPROVED] - Make redirect works for MAS and FINCAP app

README.md, db/seeds/fincap_data/lifestage.seeds.rb
[TP card](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=userstory/9508)
In order to enable feature tests for the Fincap Search feature, a new app has been created in Algolia:
`FINCAP_LOCAL_TESTING`
This allows to have a shared and common index based on the FINCAP Cms DB seed. 
In order to test pagination more records were needed. I have tried to keep it as simple as possible as this will be used mainly for testing
Instructions to reset the seed have been added to the readme. 
Dropping the DB can be dangerous as you might have to re-create users, etc. The ideal solution, in the future, would be to use a `find_or_create` seeding mechanism
=> [DEV APPROVED] [9508] Add seeds to allow feature testing on paginated search

app/controllers/api/documents_controller.rb, app/filters/document_provider.rb, spec/controllers/api/documents_controller_spec.rb, spec/factories/blocks.rb, spec/factories/pages.rb, spec/filters/document_provider_spec.rb
This PR adds an optional param to the documents  in order to override the default order (by `position` ASC, followed by `created_at` DESC for the average case).
Please note that this PR contains a lot of rubocop fixes because of the fact that these files have been touched.
=> [DEV APPROVED] Add `order_by_date` param to documents endpoint

config/initializers/inflections.rb, db/seeds/fincap_data/evidence_summary_seeds.rb, db/seeds/fincap_data/lifestage.seeds.rb, db/seeds/fincap_data/news_seeds.rb, db/seeds/fincap_data/regional_strategy_seeds.rb, db/seeds/fincap_data/what_works_seeds.rb, features/pages_form/fincap_what_works_page.feature, features/step_definitions/fincap_background_steps.rb, lib/tasks/fincap.rake
[TP Card](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiNzEyRUZDMzlENEJERUE4QjJBRDVEQzdENUE1MEE2OEIifQ==&boardPopup=userstory/9404/silent)
- Add a new layout (`What Works`). This is a copy of the `Lifestages` layout
This will provide a new URL scope. i.e /en/what_works/my-custom-page
- Amend fincap:setup rake task
- Add `what_works` seed data 
- We have discovered that tags were not properly added in the seeds. We have also simplified the logic, avoiding a second iteration over the newly created pages.
=> [DEV APPROVED] 9404 - Add a new What Works page layout

app/filters/document_provider.rb, spec/controllers/api/documents_controller_spec.rb, spec/factories/pages.rb, spec/filters/document_provider_spec.rb
- filter_by_tag was not allowing multiple tag.values using
'value =' instead of 'value IN'.
- News were duplicated if multiple tags were present, so
a 'uniq' => 'DISTINCT' clause has been added both in
filter_by_tag and order_documents filters.
=> [DEV APPROVED] - [9580] Fix multiple tags error and duplicated news

config/routes.rb, spec/controllers/api/clumps_controller_spec.rb
[TP card](https://moneyadviceservice.tpondemand.com/entity/8217-make-the-cms-clumps-api-url)
Clumps are currently exposed via the path /en/clumps.json, which is
inconsistent with other API resources such as categories and news. For
consistency, add an additional route for the mas-cms-client gem to point
to. Once the gem and clients have been updated, the old path will be
removed.
=> [DEV APPROVED] - Add an API route for clumps

config/routes.rb
This route is no longer used, now that Frontend has been updated to use v1.19 of the mas-cms-client (pointing it to `/api/:locale/clumps` for all its clump-based needs). No other client appears to use this feature, so the older route can now be removed.
=> [DEV APPROVED] Remove old clumps route

lib/cms/audit/pages.rb, spec/lib/cms/audit/pages_spec.rb
Related to: [TP Card](https://moneyadviceservice.tpondemand.com/restui/board.aspx#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiRkRBMzk3RTBGNjU3NDg1RDM4QzczMTJFNzI5MDFBN0MifQ==&boardPopup=userstory/10162/silent)
- After deployment I have tested the task and discovered
incompatibilities with the encoding. Using UTF-8 fixes the issue
- Generated file attached to the TP Card
=> [DEV APPROVED] Use UTF-8 encoding to avoid incompatibilities

.rubocop_todo.yml, app/filters/document_provider.rb, spec/factories/blocks.rb, spec/factories/pages.rb, spec/filters/document_provider_spec.rb
[TP 10209](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiRkRBMzk3RTBGNjU3NDg1RDM4QzczMTJFNzI5MDFBN0MifQ==&searchPopup=userstory/10209)
When searching documents on the evidence hub by multiple values for Topics or Client Groups, duplicate results are being displayed.
We execute a very complicated sql query in order to allow the user to filter/search documents by keyword, document type and/or various filters. Amend the query to ensure it only returns distinct results.
`DocumentProvider` builds the query, which only gets executed in the controller. We need to force the query to load to ensure the mix of raw sql and rails's `activerecord` methods used in the query, are performed in the correct order. 
Specifically, forcing …
=> [DEV APPROVED] Ensure filtering query returns unique pages

Gemfile, Gemfile.lock
Upgrade to v3.12 that came with the PACS v2.2 bump seems to break go pipelines tests as trims
the expected return carriages when parsing HTML blocks.
=> Lock Ruby Parser to v3.11

jenkins/Dockerfile, jenkins/test
Apply the new base docker image with bundled gems baked into it. 
Jenkins pipeline should be significantly quicker as this reduces duration by around 5-6 mins.
[Builder - Base image PR](https://github.com/moneyadviceservice/builder/pull/68)
=> Use sfgb-bundle-2.5.3 docker image

jenkins/test
Use rvm to select the appropriate gemset.
`bundle install` is very fast when using the correct gemset as the gems are pre-builded into the base image.
=> Use rvm to select gemset

app/serializers/block_serializer.rb
These cause lots of noise in the logs and only really need to be instrumented to debug an issue.
=> Log these messages to the debug level
